package com.texnoera.orderssoapclient.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-12-05T20:23:36.376+04:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://localhost:8080/orders", name = "OrdersPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrdersPort {

    @WebMethod(operationName = "GetOrder")
    @WebResult(name = "GetOrderResponse", targetNamespace = "http://localhost:8080/orders", partName = "GetOrderResponse")
    public GetOrderResponse getOrder(

        @WebParam(partName = "GetOrderRequest", name = "GetOrderRequest", targetNamespace = "http://localhost:8080/orders")
        GetOrderRequest getOrderRequest
    );
}
