package com.texnoera.orderssoapclient.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-12-05T20:23:36.398+04:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "OrdersPortService",
                  wsdlLocation = "file:src/main/resources/wsdl/orders.wsdl",
                  targetNamespace = "http://localhost:8080/orders")
public class OrdersPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/orders", "OrdersPortService");
    public final static QName OrdersPortSoap11 = new QName("http://localhost:8080/orders", "OrdersPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/wsdl/orders.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrdersPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/wsdl/orders.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrdersPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrdersPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrdersPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrdersPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrdersPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrdersPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrdersPort
     */
    @WebEndpoint(name = "OrdersPortSoap11")
    public OrdersPort getOrdersPortSoap11() {
        return super.getPort(OrdersPortSoap11, OrdersPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrdersPort
     */
    @WebEndpoint(name = "OrdersPortSoap11")
    public OrdersPort getOrdersPortSoap11(WebServiceFeature... features) {
        return super.getPort(OrdersPortSoap11, OrdersPort.class, features);
    }

}
